version: '3.7'

services:
    website:
        build:
          context: .
          args:
            - OPENSSL_COUNTRY_CODE=${OPENSSL_COUNTRY_CODE}
            - OPENSSL_STATE=${OPENSSL_STATE}
            - OPENSSL_LOCALITY=${OPENSSL_LOCALITY}
            - OPENSSL_ORG=${OPENSSL_ORG}
            - OPENSSL_UNIT=${OPENSSL_UNIT}
            - OPENSSL_COMMON_NAME=${OPENSSL_COMMON_NAME}
            - DB_PASSWORD=${WEBSITE_HOST_DB_PASSWORD}
        container_name: website
        ports:
          - ${WEBSITE_HOST_HTTP_PORT}:80
          - ${WEBSITE_HOST_HTTPS_PORT}:443
          - ${PHPLITEADMIN_HTTP_PORT}:17124
        volumes:
          - ./apache/container:/etc/apache2/sites-enabled
          - ./database/phpliteadmin:/home/user/database/www
          - ./www/public:/home/user/www/public
        networks:
          default_network:
            ipv4_address: 192.168.127.1
        restart: always

networks:
    default_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.127.0/16