version: '3.7'

services:
    website:
        build:
          context: .
        container_name: website
        ports:
          - ${WEBSITE_HOST_HTTP_PORT}:80
          - ${WEBSITE_HOST_HTTPS_PORT}:443
          - ${PHPLITEADMIN_HTTP_PORT}:17124
        volumes:
          - ./apache/container:/etc/apache2/sites-enabled
          - ./ssl:/var/imported/ssl
          - ./database/phpliteadmin:/home/user/database/www
          - ./www/public:/home/user/www/public
        environment: 
          - DB_PASSWORD=${WEBSITE_HOST_DB_PASSWORD}
        networks:
          default_network:
            ipv4_address: 192.168.127.1
        restart: always

networks:
    default_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.127.0/16