version: '3.7'

services:
    digital-bookmark:
        build:
          context: ./www
        container_name: digital-bookmark
        ports:
          - "${WEBSITE_HOST_HTTP_PORT}:80"
          - "${WEBSITE_HOST_HTTPS_PORT}:443"
        volumes:
          - ${APACHE_DOCKER_SETUP}/digital-bookmark.conf:/etc/apache2/sites-enabled/digital-bookmark.conf
          - ${SSL_SETUP}:/var/imported/ssl
        networks:
            drix_net:
                ipv4_address: 192.168.127.2
    # NOTICE: Do not use MySQL when setting this up on an ARM CPU
    digital-bookmark-db:
        image: mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: ${WEBSITE_HOST_DB_PASSWORD}
          MYSQL_DATABASE: ${WEBSITE_HOST_DB_DATABASE}
        volumes:
          - ./setup/mysql:/docker-entrypoint-initdb.d
        ports:
          - ${WEBSITE_HOST_DB_PORT}:3306
        networks:
          drix_net:
            ipv4_address: 192.168.127.3

networks:
    drix_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.127.0/16
